import { CKDProfile, PreventionStrategies } from "@/types/types";

export const preventionStrategies: PreventionStrategies = {
  "Stage 1": [
    "Lifestyle Modifications: Focus on healthy eating with more vegetables, fruits, whole grains, lean meats, and plant-based proteins. Avoid processed foods and sugary drinks.",
    "Blood Pressure Control: Limit sodium intake to less than 2300 mg/day to manage hypertension.",
    "Regular Monitoring: Keep track of kidney function through routine blood and urine tests.",
  ],
  "Stage 2": [
    "Dietary Adjustments: Reduce sodium intake and maintain a balanced diet with whole grains, beans, lean poultry, fish, and vegetables.",
    "Physical Activity: Exercise regularly to improve overall health and kidney function.",
    "Smoking Cessation: Avoid tobacco products to reduce kidney stress.",
    "Hydration: Stay adequately hydrated to support kidney health.",
  ],
  "Stage 3a": [
    "Nutrition: Limit sodium intake further (less than 2300 mg/day) and monitor protein consumption to reduce kidney workload.",
    "Medication Management: Avoid nephrotoxic drugs like NSAIDs and use prescribed medications for blood pressure or diabetes control.",
    "Health Monitoring: Regular checkups to track kidney function and manage related conditions like anaemia or high cholesterol.",
  ],
  "Stage 3b": [
    "Nutrition: Limit sodium intake further (less than 2300 mg/day) and monitor protein consumption to reduce kidney workload.",
    "Medication Management: Avoid nephrotoxic drugs like NSAIDs and use prescribed medications for blood pressure or diabetes control.",
    "Health Monitoring: Regular checkups to track kidney function and manage related conditions like anaemia or high cholesterol.",
  ],
  "Stage 4": [
    "Dietary Restrictions: Strictly limit sodium, potassium, and phosphate intake. Follow a diet tailored by a healthcare professional.",
    "Exercise & Weight Management: Engage in light physical activity and maintain a healthy weight to reduce disease progression risk.",
    "Medication Adherence: Use prescribed medications for cardiovascular health and avoid nephrotoxic substances.",
    "Sleep Hygiene: Prioritize adequate sleep to support overall health.",
  ],
  "Stage 5": [
    "Specialized Nutrition: Follow a carefully controlled diet with limited fluid intake while managing electrolyte levels under medical supervision.",
    "Dialysis Preparation: Consult with healthcare providers about dialysis options if kidney function is critically impaired.",
    "Emotional Support: Seek counselling or support groups to manage the emotional stress of advanced CKD.",
  ],
};

export const ckdProfiles: CKDProfile[] = [
  {
    stage: "Stage 1",
    educationYrs: 0,
    herbicideUsageHistory: 0,
    appliedHerbicideV1: 0,
    ppeUsageScoreSeverity: 0,
    wellWaterHx: 0,
    naturalWaterDrinkingV1: 1,
    exhausionV5: 0,
    exhausionSeverityV5: 0,
    jointPainV2: 0,
    naV3: 142,
    kV3: 4,
    kV4: 4.2,
    kV5: 4.2,
    hbV1: 10.3,
    hbV2: 10.6,
    hbV3: 10.8,
    hbV4: 11,
    hbV5: 11.5,
    hbV6: 11.2,
    uAcidV1: 6.63,
    uAcidV3: 5.42,
    uAcidV4: 5.82,
    uAcidV5: 7.06,
    uProteinV2: 0,
    uProteinV3: 0,
    uProteinV6: 0,
    conductivity: 149.45,
    bePpm: 0.007588997858791138,
  },
  {
    stage: "Stage 2",
    educationYrs: 0,
    herbicideUsageHistory: 0,
    appliedHerbicideV1: 0,
    ppeUsageScoreSeverity: 0,
    wellWaterHx: 0,
    naturalWaterDrinkingV1: 1,
    exhausionV5: 0,
    exhausionSeverityV5: 0,
    jointPainV2: 0,
    naV3: 142,
    kV3: 4,
    kV4: 4.2,
    kV5: 4.2,
    hbV1: 10.3,
    hbV2: 10.6,
    hbV3: 10.8,
    hbV4: 11,
    hbV5: 11.5,
    hbV6: 11.2,
    uAcidV1: 6.63,
    uAcidV3: 5.42,
    uAcidV4: 5.82,
    uAcidV5: 7.06,
    uProteinV2: 0,
    uProteinV3: 0,
    uProteinV6: 0,
    conductivity: 149.45,
    bePpm: 0.007588997858791138,
  },
  {
    stage: "Stage 3a",
    educationYrs: 7,
    herbicideUsageHistory: 1,
    appliedHerbicideV1: 0,
    ppeUsageScoreSeverity: 0,
    wellWaterHx: 1,
    naturalWaterDrinkingV1: 1,
    exhausionV5: 0,
    exhausionSeverityV5: 0,
    jointPainV2: 1,
    naV3: 141,
    kV3: 4.3,
    kV4: 4.33,
    kV5: 4.2,
    hbV1: 12.3,
    hbV2: 12.5,
    hbV3: 12.4,
    hbV4: 12.2,
    hbV5: 11.5,
    hbV6: 12.4,
    uAcidV1: 6.63,
    uAcidV3: 6.53,
    uAcidV4: 6.45,
    uAcidV5: 7.06,
    uProteinV2: 1,
    uProteinV3: 0,
    uProteinV6: 1,
    conductivity: 110.2,
    bePpm: 0.009097947173701451,
  },
  {
    stage: "Stage 3b",
    educationYrs: 5,
    herbicideUsageHistory: 0,
    appliedHerbicideV1: 0,
    ppeUsageScoreSeverity: 0,
    wellWaterHx: 1,
    naturalWaterDrinkingV1: 1,
    exhausionV5: 1,
    exhausionSeverityV5: 0,
    jointPainV2: 1,
    naV3: 141,
    kV3: 4.47,
    kV4: 4.505,
    kV5: 4.2,
    hbV1: 11.8,
    hbV2: 12,
    hbV3: 11.9,
    hbV4: 11.9,
    hbV5: 11.5,
    hbV6: 12.2,
    uAcidV1: 6.63,
    uAcidV3: 7.09,
    uAcidV4: 7.115,
    uAcidV5: 7.06,
    uProteinV2: 0,
    uProteinV3: 0,
    uProteinV6: 1,
    conductivity: 153.575,
    bePpm: 0.007588997858791138,
  },
  {
    stage: "Stage 4",
    educationYrs: 5,
    herbicideUsageHistory: 0,
    appliedHerbicideV1: 0,
    ppeUsageScoreSeverity: 0,
    wellWaterHx: 1,
    naturalWaterDrinkingV1: 1,
    exhausionV5: 0,
    exhausionSeverityV5: 0,
    jointPainV2: 1,
    naV3: 141,
    kV3: 4.6,
    kV4: 4.44,
    kV5: 4.2,
    hbV1: 11.4,
    hbV2: 11.6,
    hbV3: 11.5,
    hbV4: 11.6,
    hbV5: 11.5,
    hbV6: 12.1,
    uAcidV1: 6.82,
    uAcidV3: 7.14,
    uAcidV4: 7.1,
    uAcidV5: 7.06,
    uProteinV2: 1,
    uProteinV3: 2,
    uProteinV6: 1,
    conductivity: 151.1,
    bePpm: 0.007588997858791138,
  },
  {
    stage: "Stage 5",
    educationYrs: 5,
    herbicideUsageHistory: 1,
    appliedHerbicideV1: 0,
    ppeUsageScoreSeverity: 2,
    wellWaterHx: 1,
    naturalWaterDrinkingV1: 1,
    exhausionV5: 0,
    exhausionSeverityV5: 0,
    jointPainV2: 1,
    naV3: 140,
    kV3: 4.31,
    kV4: 4.41,
    kV5: 4.2,
    hbV1: 12,
    hbV2: 12,
    hbV3: 12.2,
    hbV4: 11.9,
    hbV5: 11.5,
    hbV6: 12.2,
    uAcidV1: 6.63,
    uAcidV3: 6.465,
    uAcidV4: 7.02,
    uAcidV5: 7.06,
    uProteinV2: 1,
    uProteinV3: 0,
    uProteinV6: 1,
    conductivity: 128.125,
    bePpm: 0.007588997858791138,
  },
];

export const names = {
  CKDu: "Evidence of CKD with no known risk factors",
  EC: "‘EC(Endemic control)’ - No evidence of CKD",
  NEC: " ‘NEC(Non Endemic Control)' - No evidence of CKD",
  ECKD: "‘ECKD(Endemic CKD)’ - Known risk factors of CKD with evidence of CKD",
  NECKD: "‘NECKD(Non-endemic CKD)’ - Evidence of CKD",
};
